version: "3.8"

services:
  db:
    image: postgres:14
    container_name: stocks-db
    restart: always
    environment:
      POSTGRES_USER: stocks
      POSTGRES_PASSWORD: stocks123
      POSTGRES_DB: stocksdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: stocks-api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://stocks:stocks123@db:5432/stocksdb
      POLYGON_API_KEY: ${POLYGON_API_KEY:-}
    ports:
      - "8000:8000"

volumes:
  pgdata:
