"""add json fields to stock

Revision ID: 32a0084a5829
Revises: 3c55e3aa5db5
Create Date: 2025-07-21 01:53:54.533298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a0084a5829'
down_revision: Union[str, Sequence[str], None] = '3c55e3aa5db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_company_code'), table_name='stocks')
    op.create_index(op.f('ix_stocks_company_code'), 'stocks', ['company_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_company_code'), table_name='stocks')
    op.create_index(op.f('ix_stocks_company_code'), 'stocks', ['company_code'], unique=False)
    # ### end Alembic commands ###
