"""create stocks table

Revision ID: 3c55e3aa5db5
Revises: 
Create Date: 2025-07-20 23:22:42.842577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c55e3aa5db5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('purchased_amount', sa.Integer(), nullable=True),
    sa.Column('purchased_status', sa.String(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('stock_values', sa.dialects.postgresql.JSONB(), nullable=True),
    sa.Column('performance_data', sa.dialects.postgresql.JSONB(), nullable=True),
    sa.Column('competitors', sa.dialects.postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_company_code'), 'stocks', ['company_code'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_company_code'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
